from os import PathLike
from pathlib import Path

class FileSource:
    def __init__(
        self,
        paths: list[str | Path | PathLike[str]],
        field: str = "text",
        separator: bytes | None = None,
    ) -> None: ...
    def __repr__(self) -> str: ...

def train_bpe(
    in_data: bytes | Path | str | FileSource,
    vocab_size: int,
    special_tokens: list[str],
    tie_breaking: str = "huggingface",
    separator: bytes | None = None,
) -> tuple[dict[int, bytes], list[tuple[bytes, bytes]]]: ...

class BPETokenizer:
    def __new__(cls) -> "BPETokenizer": ...
    def encode(self, text: bytes) -> list[int]: ...
    def encode_file(self, file_source: FileSource) -> list[list[int]]: ...
    @staticmethod
    def from_tiktoken(path: str | Path) -> "BPETokenizer": ...
    @staticmethod
    def from_hf(path: str | Path) -> "BPETokenizer": ...
    def __repr__(self) -> str: ...

class SentencePieceTokenizer:
    @staticmethod
    def from_hf(path: str | Path) -> "SentencePieceTokenizer": ...
    def encode(self, text: str) -> list[int]: ...
    def encode_no_normalize(self, text: str) -> list[int]: ...
    def encode_file(self, file_source: FileSource) -> list[list[int]]: ...
    def decode(self, tokens: list[int]) -> bytes: ...
    def __repr__(self) -> str: ...

class PretokenizerIter:
    def __iter__(self) -> "PretokenizerIter": ...
    def __next__(self) -> bytes: ...

def pretokenizer(text: bytes) -> PretokenizerIter: ...
def pretokenized_counts(
    text: bytes, separator: bytes | None = None,
) -> list[tuple[bytes, int]]: ...
